version: 0.2.0-build{build}
image: Visual Studio 2022

shallow_clone: true
clone_folder: c:\Movere

configuration:
  - Debug
  - Release
platform: Any CPU

matrix:
  fast_finish: true

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

build_script:
  - cmd: dotnet msbuild /t:Restore;Build;Pack Movere.sln

test: off

artifacts:
  - path: 'artifacts\Debug\nupkg\*.nupkg'
    name: DebugNupkg
  - path: 'artifacts\Release\nupkg\*.nupkg'
    name: ReleaseNupkg

deploy:
- provider: GitHub
  auth_token:
    secure: RTVjUSopq60NVzduiYyX2q/DPWQbp7EGQpKVjTY52hs5pi6gXP43rkocX24ddA2w
  artifact: ReleaseNupkg
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: Hn80g98uHMQpM1TktBSSgPs7b4UNNkh/463+unvkHeuSTwwnD4c7hfaHuoDBWA2K
  artifact: ReleaseNupkg
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/jp2masa/api/v2/package
  artifact: DebugNupkg
  api_key:
    secure: puOcEbngEmaVMEnUL20u4mzATgvoyaTPRWGGwE98as1+8KGY3ypOKzt5OV63duwI
  on:
    branch: master
    configuration: Debug
