name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      BUILD_NUMBER_OFFSET: ${{ vars.BUILD_NUMBER_OFFSET }}
      CONFIGURATION: ${{ matrix.configuration }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
    permissions:
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        id: checkout
      - name: "Cache: .nuke/temp, ~/.nuget/packages"
        uses: actions/cache@v5
        id: cache
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: "Prepare env: "
        id: prepare_env
        run: ./build.ps1 --target PrepareEnv
      - name: "NuGet login (OIDC → temp API key)"
        uses: NuGet/login@v1
        id: nuget_login
        if: ${{ env.SHOULD_PUBLISH_TO_NUGET }}
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: "Set NuGet API key in env"
        id: nuget_api_key
        if: ${{ env.SHOULD_PUBLISH_TO_NUGET }}
        run: |
          "NUGET_API_KEY=${{ steps.login.outputs.NUGET_API_KEY }}" >> $env:GITHUB_ENV
      - name: "Run: "
        id: run
        run: ./build.ps1
